name: "CI CD workflow"

on:
  pull_request:
    branches:
      - master
  
  push:
    branches:
      - master

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint
  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run test

  build:
    needs:
      - lint
      - test

    uses: "./.github/workflows/docker-publish.yaml"
    with:
      repo_name: my-crud-api 
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}


  deploy-staging:
    needs:
      - build

    # Add the permissions block to allow OIDC token generation
    permissions:
      id-token: write
      contents: read

    
    if: github.ref == 'refs/heads/master'
    
    uses: "./.github/workflows/ecs-deploy.yaml"
    with:
      image_name: ${{needs.build.outputs.image_name}}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

  health-check:
    needs:
      - deploy-staging
    
    runs-on: ubuntu-latest

    steps:
      # Use the static ALB DNS name. Pointing to the /health endpoint you created in server.js
      - name: Verify Staging Environment
        run: curl --fail https://simpleapi.noxvoid.top/health
  
  deploy-production:
    needs:
      - build
      - health-check

    runs-on: ubuntu-latest

    environment: production

    steps:
      - run: echo "deploying build with tag => ${{needs.build.outputs.image_name}} => to production"
      # In the future, this step will call ecs-deploy.yaml reusable workflow again, 
      # but pass in the production ECS cluster and service names.



  
  
  