name: "CI CD workflow"

on:
  pull_request:
    branches:
      - master
  
  push:
    branches:
      - master

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint
  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run test

  build:
    needs:
      - lint
      - test

    uses: "./.github/workflows/docker-publish.yaml"
    with:
      repo_name: my-crud-api 
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}


  deploy-staging:
    needs:
      - build
    
    if: github.ref == 'refs/heads/master'
    
    runs-on: ubuntu-latest

    steps:
      - run: echo "deploying build with image => ${{needs.build.outputs.image_name}} => to staging"

  health-check:
    needs:
      - deploy-staging
    
    runs-on: ubuntu-latest

    steps:
      - run: curl --fail https://jdfbusdbfdbdsbfs.com

  
  deploy-production:
    needs:
      - build
      - health-check

    runs-on: ubuntu-latest

    environment: production

    steps:
      - run: echo "deploying build with tag => ${{needs.build.outputs.image_name}} => to production"



  
  
  