name: reusable-ci
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - run: echo "hello there! in the resusable worflow step"
      - run: echo "node version is => ${{ inputs.node-version }}"
